services:
  - type: web
    name: cvflow
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: APP_NAME
        value: CVFlow
